version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - run: apt-get update
      - run: apt-get -y install git curl
      - checkout
      - run: ls
      - run: bash tg_notify.sh

workflows:
  version: 2
  build_c10:
    jobs:
      - build:
          filters:
            branches:
              only:
                - c10
